export default {
  AUTH_APP_START_UP: 'AUTH_APP_START_UP',

  AUTH_LOGIN_ATTEMPT: 'AUTH_LOGIN_ATTEMPT',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',

  AUTH_REGISTER_ATTEMPT: 'AUTH_REGISTER_ATTEMPT',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE'
};
